[tool.poetry]
name = "cc-openstack"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
doniclient = "^0.1.2"
gnocchiclient= "<= 7.0.5"
osc-placement = "<=1.7.0"
python = "^3.6"
python-blazarclient = { git = "https://github.com/ChameleonCloud/python-blazarclient", rev = "chameleoncloud/stable/train" }
python-chi = ">=0.10.0,<1.0.0"
python-chi-operator = ">=0.4.1"
python-cinderclient = "<=5.0.2"
python-dracclient = "^6.0.0"
python-glanceclient = "<=2.17.1"
python-heatclient = { git = "https://github.com/ChameleonCloud/python-heatclient", rev = "stable/rocky" }
python-ironicclient = "<=3.1.2"
python-keystoneclient = "<=3.21.0"
python-neutronclient = "<=6.14.1"
python-novaclient = "<=15.1.1"
python-openstackclient = "<=4.0.2"
python-swiftclient= "<=3.8.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
