#!/usr/bin/env bash
# Checks the status of a Placement resource provider for Ironic nodes.
set -e -u -o pipefail

all_providers=$(openstack resource provider list -f json)

provider_by_name() {
  local name="$1"
  jq -r "map(select(.name == \"$name\"))[0].uuid" <<<"$all_providers"
}

all_nodes=$(openstack baremetal node list -f json)
available_node_uuids=$(jq -r 'map(select(
  .["Provisioning State"] == "available" and
  .["Maintenance"] == false
))[].UUID' <<<"$all_nodes")

for node in $available_node_uuids; do
  provider="$(provider_by_name $node)"
  in_use=$(openstack resource provider usage show "$provider" -f json \
    | jq -r 'map(select(.resource_class == "CUSTOM_BAREMETAL"))[0].usage') || break
  reserved=$(openstack resource provider inventory show "$provider" CUSTOM_BAREMETAL -f json \
    | jq -r '.reserved') || break
  if [[ $in_use -gt 0 ]]; then
    allocation=$(openstack resource provider show --allocations "$provider" -f json \
     | jq -r '.allocations | keys[]')
    echo "ERROR ($node): allocations exist"
    echo "  This indicates that for some reason an allocation was made"
    echo "  against the resource provider, but was not cleaned up."
    echo "  Suggestion: delete the allocation."
    echo
    echo "  openstack resource provider allocation delete $allocation"
    echo
  elif [[ $reserved -gt 0 ]]; then
    echo "ERROR ($node): inventory already reserved"
    echo "  This indicates that for some reason there is a reservation for the"
    echo "  resource provider's inventory. Suggestion: reset the inventory."
    echo
    echo "  openstack resource provider inventory set $provider \\"
    echo "    --resource CUSTOM_BAREMETAL:total=1 --resource CUSTOM_BAREMETAL:max_unit=1 \\"
    echo "    --resource CUSTOM_BAREMETAL:reserved=0"
    echo
  fi
done
