#!/usr/bin/env bash

floating_ips=$(openstack floating ip list -f json \
  | jq -r 'map(select(.["Port"] != null)) | map(.["Floating IP Address"])[]')

unreachable=$(xargs -n1 -I% -P10 sh -c 'ping -c1 -W1 % >/dev/null || echo % not reachable' <<<"$floating_ips")

total_cnt=$(wc -l <<<"$floating_ips")
unreachable_cnt=$(wc -l <<<"$unreachable")

(
  echo "Total: $total_cnt"
  echo "Unreachable: $unreachable_cnt"
  echo "Pct: $(echo "scale=2; x=$unreachable_cnt/$total_cnt; x*100" | bc)%"
  echo "Summary:"
  echo
) | column -t

echo "$unreachable"
