#!/usr/bin/env bash

openstack floating ip list -f json \
  | jq -r 'map(select(.["Port"] != null)) | map(.["Floating IP Address"])[]' \
  | xargs -n1 -I% -P10 sh -c 'nc -zw1 % 22 || echo % not reachable'
