#!/usr/bin/env bash
# Creates a one-off lease for a given node_type, provisions it with an image,
# then drops you inside. The lease is short-lived by default (1 day).
set -e -u -o pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

node_type="${1:-}"
IMAGE="CC-CentOS7"

for i in "$@"; do
case $i in
    --image=*)
    IMAGE="${i#*=}"
    shift
    ;;
    *)
      # unknown option
    ;;
esac
done

lease_name="$USER-give-me-a-$node_type"
lease_json="$(blazar lease-create -f json \
  --physical-reservation "min=1,max=1,resource_properties=[\"=\", \"\$node_type\", \"$node_type\"]" \
  "$lease_name")"
lease_id="$(jq -r .ID <<<"$lease_json")"

# Wait for lease to be ready
while true; do
  lease_status_json="$(blazar lease-show -f json "$lease_id")"
  action="$(jq -r .action <<<"$lease_status_json")"
  status="$(jq -r .status <<<"$lease_status_json")"
  if [[ "$action" == "START" && "$status" == "COMPLETE" ]]; break;
done

export IMAGE
"$DIR/provision-nodes" --lease "$lease_name" --key-pair jason
