#!/usr/bin/env bash

# Pre-fetch token
token=$(openstack token issue -f value -c id)
export OS_TOKEN=$token
export OS_AUTH_TYPE=token
unset OS_CLOUD
unset OS_PASSWORD
unset OS_USERNAME
unset OS_USER_DOMAIN_NAME

executor() {
  while read network; do
    openstack network show $network -f json \
      | jq -r '.["provider:physical_network"] + "\t" + (.["provider:segmentation_id"] | tostring) + "\t" +
               .name + "\t" + .project_id'
  done
}
export -f executor

rows=$(openstack network list -f value -c ID \
  | SHELL=$(type -p bash) parallel --pipe executor --progress -j 10 \
  | sort -k2 -n)

tab=$(echo -ne "\t")
printf "physical_network\tsegmentation_id\tname\tproject_id\n$rows\n" \
  | column -t -s"$tab"
