#!/usr/bin/env bash
# Checks the status of a Placement resource provider for Ironic nodes.
set -e -u -o pipefail

all_providers=$(openstack resource provider list -f json)

provider_by_name() {
  local name="$1"
  jq -r "map(select(.name == \"$name\"))[0].uuid" <<<"$all_providers"
}

all_nodes=$(openstack baremetal node list -c "UUID" -c "Provisioning State" -f json)
available_node_uuids=$(jq -r 'map(select(.["Provisioning State"] == "available"))[].UUID' <<<"$all_nodes")

for node in $available_node_uuids; do
  in_use=$(openstack resource provider usage show "$(provider_by_name $node)" -f json \
    | jq 'map(select(.resource_class == "CUSTOM_BAREMETAL"))[0].usage') || break
  if [[ $in_use -gt 0 ]]; then
    echo "ERROR: node $node available, but marked as used"
  fi
done
