#!/usr/bin/env bash
# Checks the status of a Placement resource provider for Ironic nodes.
set -e -u -o pipefail

resource_class=CUSTOM_BAREMETAL

if [[ $# == 0 ]]; then
  nodes=$(openstack baremetal node list -f value -c UUID)
else
  nodes=$@
fi

for node in $nodes; do
  provider_uuid=$(openstack resource provider list --name=$node -f value -c uuid)
  reserved_count=$(openstack resource provider inventory show $provider_uuid $resource_class -f json \
    | jq -r '.reserved')
  used_count=$(openstack resource provider usage show $provider_uuid -f json \
    | jq -r "map(select(.resource_class==\"$resource_class\"))[].usage")
  if [[ $reserved_count != $used_count ]]; then
    echo "$node has bad resource provider state: reserved=$reserved_count, used=$used_count"
  fi
done
